name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Install dependencies
        run: |
          go mod tidy
          go install gotest.tools/gotestsum@latest

      - name: Run tests
        run: make tests

      - name: Run tests and generate coverage report
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: make coverage

      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./cover.out
          name: codecov-p2p-agent
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
