name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22'


    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run:  |
        go install gotest.tools/gotestsum@latest
        go install github.com/golang/mock/mockgen@v1.6.0
        make mocks
        make test

    - name: Run tests and generate coverage report
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run:  |
        make mocks
        make coverage

    - uses: codecov/codecov-action@v4
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      with:
        fail_ci_if_error: true
        files: ./cover.out
        name: codecov-p2p-agent
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true