name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22'

    - name: Install dependencies
      run: go mod download

    - name: Run tests and generate coverage report
      run: make coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v4.3.5
      with:
        name: coverage-report
        path: cover.html
